### ISSUE TITLE
F-droid version stuck to 2.5?

### ISSUE THREAD

**Issue by returntrip** [tasomaniac/OpenLinkWith#67]
I do not see Version 2.8 in F-droid, could it be made available there please?

**Comment by tasomaniac** [comment]
Thanks for taking time to open the issue. Unfortunately the update process on F-droid is very difficult and manual. I gave up because of unresponsiveness. There is a way to automate the updates but I've been told that it is not possible since I use more dynamic versioning in the repo.

**Comment by IzzySoft** [comment]
auto-updates don't work because they require literal values for versionName & versionCode, while `build.gradle` here [uses variables instead](https://github.com/tasomaniac/OpenLinkWith/blob/master/app/build.gradle#L15). If you see a way to provide the literal values some way (eg in a separate file, the way Flutter apps do, just a single line like `version: 2.8+20801` with `2.8` being versionName and `20801` versionCode), we could check if that could be used.

Apart from that, unless the build process changed, triggering an update is not that hard either: you'd need to open a merge request for the metadata file with the new build block added and CV/CVC adjusted. If I guessed above values correctly, the end of that file would look like

```yaml
  - versionName: 2.9-floss
    versionCode: 20901
    commit: '2.9'
    subdir: app
    gradle:
      - floss
    prebuild: sed -i -e '/playImplementation/,+2d' -e '/fabric/d' -e '/SimpleDateFormatConstant/d'
        build.gradle ../build.gradle
    
MaintainerNotes: |-
    Summary and Description have been removed since upstream provides
    much better ones via Triple-T Gradle Play Publisher:
    https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots
    
AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: 2.9-floss
CurrentVersionCode: 20901
```

I'm just not sure about the versionCode :wink:
